services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - USERNAME=myusername
      - PASSWORD=mypassword

    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.9'
          #memory: 800M
        # reservations:
        #   cpus: '0.60'
        #   memory: 300M
    ports:
      - "3128:3128"
